### PR TITLE
Add ability to fetch variant data

### PR DESCRIPTION
**Pull request by deepakunni3**
@nathandunn 

added the ability to fetch variant data.

There is still some issue with how the track object (not Apollo's track object but the local component's track object) is being sent to the function as argument.

Feel free to merge and add to it.
If not, I can continue hacking on this tomorrow too.

### CODE REVIEW

**Comment by nathandunn** [comment]
Getting this: 

screen shot 2018-10-12 at 5 41 06 pm

**Comment by nathandunn** [comment]
Or is it supposed to be going to a local server?

**Comment by nathandunn** [comment]
@deepakunni3  Can I close this for now (but keep the branch?)

**Comment by deepakunni3** [comment]
@nathandunn Sure, feel free to close it

**Comment by nathandunn** [comment]
We'll re-open later once we've re-established what we are doign with it (and re-branched)

**Pull request closed without merging**
