### PR TITLE
Update variant v1

### PR DESCRIPTION
**Pull request by nathandunn**

### CODE REVIEW

**Comment by nathandunn** [comment]
@pjhale  I think this will work when build is done building, but if you could double-check this (should be ready in about 30 minutes)

**Comment by nathandunn** [comment]
the big changes are the the variants (a) show up and (b) both the symbol (not the name) and the ID are present:

    symbol: sox1<sup>123</sup> (FBAllele:1231)

Something like that.

**Comment by pjhale** [comment]
This is working for me however I'm noticing a few things.  The consequence colors have changed and along with that the consequence field in the popup is all one long string, no delimiter.  I am guessing these are related.

**Comment by nathandunn** [comment]
@pjhale  that is probably correct. Are you able to complete this and I can focus on the Apollo changes?

**Comment by nathandunn** [comment]
(to fix the weird symbolds

**Comment by pjhale** [comment]
@nathandunn should look more familiar.

**Pull request merged**
